# This workflow will run server tests

name: Node.js Server tests

on:
  push:
    paths:
    - 'server/**'
    branches: [ main, devel ]
  pull_request:
    paths:
    - 'server/**'
    branches: [ main, devel ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      working-directory: ./server

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
